<?php

/**
 * @file
 * This is the file that provides a quick look to show the main Drupal hooks for presenting to BITS AMERICAS
 *
 * @author Edwin Vega Moreno ('Web Developer ('Drupal')')
 */

/**
 * Implements hook_menu().
 */
function bitsamericas_menu() {

	$items = array();

	$items['city/form'] = array(
    'title' => t('Technical Test for Bits Americas'),
    'description' => 'testing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bitsamericas_form'),
    'access callback' => TRUE,
    'file' => 'includes/bitsamericas.forms.inc',
	);
	$items['bitsamericas/seetings'] = array(
    'title' => 'Connection settings endpoint',
    'description' => 'testing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('settings_endpoint_form'),
    'access callback' => 'user_access',
    'access arguments' => array('acces to connection'),
    'file' => 'includes/bitsamericas.forms.inc',
	);
	
	return $items;
}

/**
 * Implements hook_permission().
 */
function bitsamericas_permission() {
   return array(
     'acces to menu Bits' =>  array(
       'title' => t('Acces to Bits form'),
       'description' => t('Allows access to fill out the Bits form'),
     ),
   );
}

/**
 * Implements hook_help().
 */
function bitsamericas_help($path, $arg) {
   switch ($path) {
     case 'admin/help#bitsamericas':
       return check_markup(file_get_contents( dirname(__FILE__) . "/README.txt") );
   }
}

/**
 * Implements hook_block_info().
 */
function bitsamericas_block_info() {
	$blocks = array();
	$blocks['block_form_city'] = array(
		'info' => t('Bits form to select info about one city'),
		'region' => 'content',
		'status' => TRUE,
		'visibility' => BLOCK_VISIBILITY_LISTED,
		'pages' => "<front>",
		'cache' => 'DRUPAL_NO_CACHE',
	);
	
	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bitsamericas_block_view($delta = '') {
	module_load_include('inc', 'bitsamericas', 'includes/bitsamericas.forms');
 	$block = array();
  switch ($delta) {
    case 'block_form_city':
      $block['content'] = drupal_get_form('bitsamericas_form');
      break;
  }
  	
  return $block;
}

function ajax_city_callback($form, $form_state) {
	module_load_include('inc', 'bitsamericas', 'includes/bitsamericas.functions');
	$data = _retrieve_connection_data();
  $selector = '#after_div';
  $city = $form_state['values']['city'];
  $url = $data[0]->endpoint_base . $city . '&appid=' . $data[0]->appid . '&units=' . $data[0]->units;
	$request = drupal_http_request($url);
	$decoded_json = drupal_json_decode($request->data);
	$output = "<table><thead><tr><th>Ciudad</th><th>Temp</th><th>Humidity</th><th>Temp. min</th><th>Temp. max</th></tr></thead><tbody>";
	$output .= "<tr><td>" . $decoded_json['name'] . "</td>";
	$output .= "<td>" . $decoded_json['main']['temp'] . "</td>";
	$output .= "<td>Long: " . $decoded_json['main']['humidity'] . " / Lat:  " . $decoded_json['coord']['lat'] . "</td>";
	$output .= "<td>" . $decoded_json['main']['temp_min'] . " °C</td>";
	$output .= "<td>" . $decoded_json['main']['temp_max'] . " °C</td></tr>";
	$output .= "</tbody></table>";
  $commands = array();
  $commands[] = ajax_command_after($selector, $output);

  return array('#type' => 'ajax', '#commands' => $commands);
}